### ISSUE TITLE
get_hmac_and_key.py invalid syntax error

### ISSUE THREAD

**Issue by jrussell88** [pazaan/decoding-contour-next-link#26]
I get the following error when I run _get_hmac_and_key.py_:
> /git$ python3 -m decoding-contour-next-link.get_hmac_and_key.py
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/media/john/Home/john/git/decoding-contour-next-link/get_hmac_and_key.py", line 36
    print "INT RESPONSE: {0}".format( int1 )
                            ^
SyntaxError: invalid syntax

Can anyone suggest the cause of the problem?

**Comment by mortlind** [comment]
I think the HMAC and key are not needed anymore. Try using `read_minimed_next24` without downloading HMAC and key first.

**Comment by paulokow** [comment]
Reference to `get_hmac_and_key.py` removed from README now
