### ISSUE TITLE
read_minimed_next24.py: No module named 'hid' error

### ISSUE THREAD

**Issue by jrussell88** [pazaan/decoding-contour-next-link#27]
I'm running Ubuntu 17.04; I installed hidapi, but _read_minimed_next24_ is failing with the error:
`ImportError: No module named 'hid'`

> /git$ python3 -m decoding-contour-next-link.read_minimed_next24
Traceback (most recent call last):
  File "/media/john/Home/john/git/decoding-contour-next-link/read_minimed_next24.py", line 8, in <module>
    import hid # pip install hidapi - Platform independant
ImportError: No module named 'hid'
During handling of the above exception, another exception occurred:
Traceback` (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/john/Home/john/git/decoding-contour-next-link/read_minimed_next24.py", line 9, in <module>
    except WindowsError:
NameError: name 'WindowsError' is not defined

Can anyone suggest what might be causing this?

**Comment by mortlind** [comment]
`# pip3 install hid`

**Comment by jrussell88** [comment]
I reinstalled the dependencies for pip3;

> $ sudo -H pip3 install cython
$ sudo -H pip3 install hidapi
$ sudo -H pip3 install requests astm PyCrypto crc16 python-dateutil
$ sudo -H pip3 install python-lzo

Then:

> /git$ pip3 install -r requirements.txt

As I was still getting file errors: 

> /git$ python3 -m decoding-contour-next-link.read_minimed_next24
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/john/Home/john/git/decoding-contour-next-link/read_minimed_next24.py", line 1331, in <module>
    downloadPumpSession(pumpDownload)
  File "/media/john/Home/john/git/decoding-contour-next-link/read_minimed_next24.py", line 1225, in downloadPumpSession
    mt.openDevice()
  File "/media/john/Home/john/git/decoding-contour-next-link/read_minimed_next24.py", line 759, in openDevice
    self.device.open( self.USB_VID, self.USB_PID )
  File "hid.pyx", line 66, in hid.device.open
OSError: open failed


I ran the commands as root:

> /git$ sudo python -m decoding-contour-next-link.read_minimed_next24
/git$ sudo python3 -m decoding-contour-next-link.read_minimed_next24

which worked.

**Comment by mortlind** [comment]
@jrussell88 I am currently fighting this problem with opening the HID as ordinary user. I am fixing the permissions with UDev rules, which looks like they work. I am out of my depth here, since on some PCs I still get errors when opening the device, even though the permissions seems to be allowing me.
