### ISSUE TITLE
missing dependency in readme?

### ISSUE THREAD

**Issue by bertBruynooghe** [pazaan/decoding-contour-next-link#35]
Being new with Python and contour next link, I followed the readme, and got this finally:

    python -m decoding-contour-next-link.read_minimed_next24
    Traceback (most recent call last):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 151, in _run_module_as_main
        mod_name, loader, code, fname = _get_module_details(mod_name)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 101, in _get_module_details
        loader = get_loader(mod_name)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 464, in get_loader
        return find_loader(fullname)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 474, in find_loader
        for importer in iter_importers(fullname):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 430, in iter_importers
        __import__(pkg)
      File "decoding-contour-next-link/__init__.py", line 2, in <module>
        from .read_minimed_next24 import *
      File "decoding-contour-next-link/read_minimed_next24.py", line 9, in <module>
        except WindowsError:
    NameError: name 'WindowsError' is not defined

Any suggestions?

**Comment by sdshlanta** [comment]
try adding the following line to `read_minimed_next24.py`

```
try:
    WindowsError
except NameError:
    WindowsError = Exception```

That should create a dummy `WindowsError` with the same interface as a standard exception.
