### ISSUE TITLE
python -m decoding-contour-next-link.read_minimed_next24 fails 

### ISSUE THREAD

**Issue by tjgordon** [pazaan/decoding-contour-next-link#48]
Calling the module from the parent directory as described in the readme fails:

```
tgordon:~$ python3 -m decoding-contour-next-link.read_minimed_next24
/usr/lib/python3.8/runpy.py:126: RuntimeWarning: 'decoding-contour-next-link.read_minimed_next24' found in sys.modules after import of package 'decoding-contour-next-link', but prior to execution of 'decoding-contour-next-link.read_minimed_next24'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/tgordon/decoding-contour-next-link/read_minimed_next24.py", line 1571, in <module>
    downloadPumpSession(pumpDownload)
  File "/home/tgordon/decoding-contour-next-link/read_minimed_next24.py", line 1465, in downloadPumpSession
    mt.openDevice()
  File "/home/tgordon/decoding-contour-next-link/read_minimed_next24.py", line 764, in openDevice
    self.device.open( self.USB_VID, self.USB_PID )
  File "hid.pyx", line 66, in hid.device.open
OSError: open failed
```

I tested with two different Contour Next Link 2.4 units on Ubuntu 20.04. The error is identical before and after unplugging either CNL.

**Comment by Whosayink** [comment]
Try with python2
